### ISSUE TITLE
Can't seem to scroll down to buttons in Genotype Builder window

### ISSUE THREAD

**Issue by borisofmuscovy** [idekerlab/DCell#34]
As described in title. Reproduced on Safari and Chrome in macOS. There doesn't seem to be a way to reach the buttons at all. This is as far as I get:
<img width="448" alt="screen shot 2018-03-07 at 19 35 41" src="https://user-images.githubusercontent.com/21023619/37111065-0b319d8a-223f-11e8-9b0f-ccbed1b1c3aa.png">

**Comment by keiono** [comment]
Thanks for reporting.  I confirmed the issue and it will be fixed today.

**Comment by keiono** [comment]
Resolved in current version.
